# Generated by Django 2.2.5 on 2019-09-28 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Detail',
            fields=[
                ('student_name', models.CharField(help_text='Input Candidate Name', max_length=20)),
                ('college_name', models.CharField(help_text='Input College Name Who issue Certificate', max_length=50)),
                ('event', models.CharField(default='COMPETITION', help_text='Select Valid Choice', max_length=12)),
                ('event_name', models.CharField(max_length=100)),
                ('about_event', models.CharField(help_text='About Certification', max_length=100)),
                ('position_category', models.CharField(blank=True, default='Participation', help_text='Select Valid Choice', max_length=20, null=True)),
                ('position', models.PositiveIntegerField(blank=True, help_text='Input Position', null=True)),
                ('certification_date', models.DateField(default=datetime.date.today)),
                ('email1', models.EmailField(max_length=254)),
                ('issue_by', models.CharField(max_length=50)),
                ('unique_id1', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
